data:
  background:
    slice: 900
    type:
      pixel: pixel
  lineouts:
    end: 940
    skip: 10
    start: 800
    type:
      ps: ps
  shotnum: 101675
mlflow:
  experiment: inverse-thomson-scattering
  run: test
other:
  PhysParams:
    widIRF:
      ang_FWHM_ele: 1.0
      spect_FWHM_ele: 0.9
      spect_stddev_ele: 0.1
      spect_stddev_ion: 0.015
  calc_sigmas: false
  extraoptions:
    fit_EPWb: true
    fit_EPWr: true
    fit_IAW: false
    load_ele_spec: true
    load_ion_spec: false
    spectype: temporal
  refit: false
  refit_thresh: 5.0
parameters:
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 10.0
      val: 0.0
    Va:
      active: false
      angle: 0.0
      lb: -20.5
      ub: 20.5
      val: 0.0
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp2:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp3:
      active: false
      lb: 0.01
      ub: 3.75
      val: 1.0
    lam:
      active: false
      lb: 523.0
      ub: 528.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    type:
      active: false
      general: general
    ud:
      active: false
      angle: 0.0
      lb: -10.0
      ub: 10.0
      val: 0.0
  species1:
    Te:
      active: true
      lb: 0.01
      ub: 1.5
      val: 0.2
    fe:
      active: false
      dim: 1
      fe_decrease_strict: false
      lb: -100.0
      length: 3999
      m_asym: 1.0
      m_theta: 0.0
      symmetric: false
      temp_asym: 1.0
      type:
        DLM: DLM
      ub: -0.5
      v_res: 0.05
      val: '[]'
    m:
      active: false
      intens: 2.0
      lb: 2.0
      matte: false
      ub: 5.0
      val: 2.0
    ne:
      active: true
      lb: 0.03
      ub: 1.0
      val: 0.08
    type:
      active: false
      electron: electron
  species2:
    A:
      active: false
      val: 40.0
    Ti:
      active: false
      lb: 0.01
      same: false
      ub: 1.0
      val: 0.08
    Z:
      active: false
      lb: 1.0
      ub: 18.0
      val: 10.0
    fract:
      active: false
      val: 1.0
    type:
      active: false
      ion: ion
