/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and MLflow reachability */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run detail with config tree and artifact listing */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream an artifact
         * @description Serve artifact bytes through the API so the frontend needs no S3 credentials.
         */
        get: operations["get_artifact_api_runs__run_id__artifacts__artifact_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What interactive views this run supports
         * @description Probe before rendering.
         *
         *     Always answers -- an angular or pre-contract run gets ``supported: false``
         *     plus a reason rather than an error, so the run detail view can pick a layout
         *     in one call.
         */
        get: operations["get_availability_api_runs__run_id__datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/lineout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Measured vs fitted spectrum at one lineout
         * @description The interactive replacement for the pre-rendered lineout PNGs.
         *
         *     IRF and noise components are not in the netCDF datasets, so they are reported
         *     as unavailable rather than fabricated -- see ``components_unavailable``.
         */
        get: operations["get_lineout_api_runs__run_id__lineout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/metrics/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full metric history (loss curves)
         * @description Metric keys contain spaces (``overall loss``), so they arrive URL-encoded.
         */
        get: operations["get_metric_history_api_runs__run_id__metrics__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fitted parameters vs lineout, with uncertainties where available */
        get: operations["get_profiles_api_runs__run_id__profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/spectrogram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 2D spectrogram, downsampled server-side */
        get: operations["get_spectrogram_api_runs__run_id__spectrogram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactEntry */
        ArtifactEntry: {
            /** Is Dir */
            is_dir: boolean;
            /** Path */
            path: string;
            /** Size */
            size?: number | null;
        };
        /** CacheStats */
        CacheStats: {
            /** Bytes */
            bytes: number;
            /** Directory */
            directory: string;
            /** Entries */
            entries: number;
            /** Max Bytes */
            max_bytes: number;
        };
        /**
         * DatasetAvailability
         * @description What the interactive views can render for a run, and why not when they can't.
         *
         *     The run detail view calls this first to choose a layout, so it answers for
         *     every run -- including angular and pre-contract ones -- instead of erroring.
         */
        DatasetAvailability: {
            kind: components["schemas"]["DatasetKind"];
            /**
             * Message
             * @description Human-readable explanation, safe to show
             */
            message?: string | null;
            /**
             * Profiles Available
             * @default false
             */
            profiles_available: boolean;
            reason?: components["schemas"]["UnavailableReason"] | null;
            /**
             * Sigmas Available
             * @description Whether uncertainties exist; calc_sigmas is off by default
             * @default false
             */
            sigmas_available: boolean;
            /**
             * Spectra
             * @default []
             */
            spectra: components["schemas"]["SpectrumInfo"][];
            /**
             * Supported
             * @description True when at least one spectrum can be served
             */
            supported: boolean;
            /**
             * Unavailable Fields
             * @description Fields a client might expect but which cannot be served, mapped to why
             */
            unavailable_fields?: {
                [key: string]: string;
            };
        };
        /**
         * DatasetKind
         * @description What kind of Thomson run the artifacts say this is.
         * @enum {string}
         */
        DatasetKind: "one_d" | "angular" | "unknown";
        /**
         * DatasetUnavailableBody
         * @description The reason payload itself.
         */
        DatasetUnavailableBody: {
            /** Detail */
            detail: string;
            reason: components["schemas"]["UnavailableReason"];
        };
        /**
         * DatasetUnavailableResponse
         * @description Error body for the dataset endpoints, carrying a reason code.
         *
         *     Nested under ``detail`` because that is what actually goes over the wire:
         *     FastAPI wraps whatever an ``HTTPException`` carries in a ``detail`` key. A
         *     flat declaration would make the generated client read ``err.reason`` and get
         *     ``undefined`` on exactly the angular-vs-missing distinction these endpoints
         *     exist to make legible.
         */
        DatasetUnavailableResponse: {
            detail: components["schemas"]["DatasetUnavailableBody"];
        };
        /** Experiment */
        Experiment: {
            /** Artifact Location */
            artifact_location?: string | null;
            /**
             * Creation Time
             * @description Unix epoch milliseconds
             */
            creation_time?: number | null;
            /** Experiment Id */
            experiment_id: string;
            /**
             * Last Update Time
             * @description Unix epoch milliseconds
             */
            last_update_time?: number | null;
            /** Lifecycle Stage */
            lifecycle_stage?: string | null;
            /** Name */
            name: string;
            /**
             * Tags
             * @default {}
             */
            tags: {
                [key: string]: string;
            };
        };
        /** ExperimentList */
        ExperimentList: {
            /** Experiments */
            experiments: components["schemas"]["Experiment"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            cache: components["schemas"]["CacheStats"];
            /**
             * Mlflow Error
             * @description Why the tracking server could not be reached
             */
            mlflow_error?: string | null;
            /** Mlflow Reachable */
            mlflow_reachable: boolean;
            /** Mlflow Tracking Uri */
            mlflow_tracking_uri: string;
            /**
             * Status
             * @description 'ok' when MLflow is reachable, 'degraded' otherwise
             */
            status: string;
        };
        /** Lineout */
        Lineout: {
            /**
             * Components
             * @description Always empty today; see components_unavailable
             */
            components?: {
                [key: string]: (number | null)[];
            };
            /**
             * Components Unavailable
             * @description Why IRF/noise components are absent, when they are
             */
            components_unavailable?: string | null;
            /**
             * Data
             * @description Measured spectrum
             */
            data: (number | null)[];
            /**
             * Fit
             * @description Fitted spectrum
             */
            fit: (number | null)[];
            /**
             * Index
             * @description Resolved lineout index; negative inputs are normalized
             */
            index: number;
            /** Lineout Count */
            lineout_count: number;
            /**
             * Residual
             * @description Derived as data - fit
             */
            residual: (number | null)[];
            /** Wavelength */
            wavelength: (number | null)[];
            /** Which */
            which: string;
            /** X Label */
            x_label: string;
            /**
             * X Value
             * @description Position of this lineout on the lineout axis
             */
            x_value: number;
            /** Y Label */
            y_label: string;
        };
        /** MetricHistory */
        MetricHistory: {
            /** Key */
            key: string;
            /** Points */
            points: components["schemas"]["MetricPoint"][];
        };
        /** MetricPoint */
        MetricPoint: {
            /** Step */
            step: number;
            /** Timestamp */
            timestamp?: number | null;
            /** Value */
            value: number;
        };
        /** MetricSummary */
        MetricSummary: {
            /** Key */
            key: string;
            /** Step */
            step?: number | null;
            /** Timestamp */
            timestamp?: number | null;
            /** Value */
            value: number;
        };
        /** ProfileSeries */
        ProfileSeries: {
            /**
             * Name
             * @description Column name from learned_parameters.csv, e.g. 'Te_electron'
             */
            name: string;
            /**
             * Sigma
             * @description Per-point uncertainty when the run computed sigmas
             */
            sigma?: (number | null)[] | null;
            /** Values */
            values: (number | null)[];
        };
        /** Profiles */
        Profiles: {
            /**
             * Lineout Pixels
             * @description Detector pixel index per lineout, when logged
             */
            lineout_pixels?: number[] | null;
            /** Series */
            series: components["schemas"]["ProfileSeries"][];
            /** Sigmas Available */
            sigmas_available: boolean;
            /**
             * X
             * @description Lineout axis coordinates
             */
            x: (number | null)[];
            /** X Label */
            x_label: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Artifact Uri */
            artifact_uri?: string | null;
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactEntry"][];
            /**
             * Config
             * @description Logged params unflattened back into the nested config tree
             */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Config Flat
             * @description The raw flattened params exactly as MLflow stores them
             */
            config_flat?: {
                [key: string]: string;
            };
            /**
             * Config Unflatten Error
             * @description Set when params could not be unflattened (colliding dotted keys); config falls back to empty
             */
            config_unflatten_error?: string | null;
            /**
             * Duration S
             * @description Computed from start/end time; null while running
             */
            duration_s?: number | null;
            /**
             * End Time
             * @description Unix epoch milliseconds
             */
            end_time?: number | null;
            /** Experiment Id */
            experiment_id: string;
            /** Experiment Name */
            experiment_name?: string | null;
            /** Final Loss */
            final_loss?: number | null;
            /**
             * Loss Key
             * @description Which metric final_loss was read from
             */
            loss_key?: string | null;
            /**
             * Manifest
             * @description Parsed manifest.json when the run logged one (ergodicio/tsadar#116)
             */
            manifest?: {
                [key: string]: unknown;
            } | null;
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["MetricSummary"][];
            /**
             * Mlflow Run Url
             * @description Deep link to this run in the MLflow UI
             */
            mlflow_run_url?: string | null;
            /** Run Id */
            run_id: string;
            /** Run Name */
            run_name?: string | null;
            /**
             * Shot
             * @description Shot number, from the data.shotnum param
             */
            shot?: string | null;
            /**
             * Spectype
             * @description Spectrum type as logged ('temporal', 'imaging', 'angular', 'angular_full'). A HINT, NOT GROUND TRUTH: log_mlflow runs before fitter.fit, and loadData overwrites spectype from the data file during prepare, so a deck saying 'temporal' run against angular data logs 'temporal'. Confirm from artifact shape (binary/fit_and_data.nc is angular; ele_/ion_fit_and_data.nc is 1D) before rendering anything axis-dependent.
             */
            spectype?: string | null;
            /**
             * Stage
             * @description tsadar's own progress tag ('preprocessing', 'minimizing', ... 'completed'), when logged
             */
            stage?: string | null;
            /**
             * Start Time
             * @description Unix epoch milliseconds
             */
            start_time?: number | null;
            /**
             * Status
             * @description MLflow lifecycle status: RUNNING/FINISHED/FAILED/KILLED
             */
            status?: string | null;
            /**
             * Tags
             * @default {}
             */
            tags: {
                [key: string]: string;
            };
            /** User */
            user?: string | null;
        };
        /** RunPage */
        RunPage: {
            /**
             * Next Page Token
             * @description Opaque cursor for the next page. MLflow paginates by token, not offset; null means last page.
             */
            next_page_token?: string | null;
            /** Page Size */
            page_size: number;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunSummary
         * @description One row of the run browser table.
         */
        RunSummary: {
            /**
             * Duration S
             * @description Computed from start/end time; null while running
             */
            duration_s?: number | null;
            /**
             * End Time
             * @description Unix epoch milliseconds
             */
            end_time?: number | null;
            /** Experiment Id */
            experiment_id: string;
            /** Experiment Name */
            experiment_name?: string | null;
            /** Final Loss */
            final_loss?: number | null;
            /**
             * Loss Key
             * @description Which metric final_loss was read from
             */
            loss_key?: string | null;
            /** Run Id */
            run_id: string;
            /** Run Name */
            run_name?: string | null;
            /**
             * Shot
             * @description Shot number, from the data.shotnum param
             */
            shot?: string | null;
            /**
             * Spectype
             * @description Spectrum type as logged ('temporal', 'imaging', 'angular', 'angular_full'). A HINT, NOT GROUND TRUTH: log_mlflow runs before fitter.fit, and loadData overwrites spectype from the data file during prepare, so a deck saying 'temporal' run against angular data logs 'temporal'. Confirm from artifact shape (binary/fit_and_data.nc is angular; ele_/ion_fit_and_data.nc is 1D) before rendering anything axis-dependent.
             */
            spectype?: string | null;
            /**
             * Stage
             * @description tsadar's own progress tag ('preprocessing', 'minimizing', ... 'completed'), when logged
             */
            stage?: string | null;
            /**
             * Start Time
             * @description Unix epoch milliseconds
             */
            start_time?: number | null;
            /**
             * Status
             * @description MLflow lifecycle status: RUNNING/FINISHED/FAILED/KILLED
             */
            status?: string | null;
            /** User */
            user?: string | null;
        };
        /** Spectrogram */
        Spectrogram: {
            /**
             * Downsample Factors
             * @description Block-averaging factors applied per axis. The lineout axis is spared where possible.
             */
            downsample_factors: {
                [key: string]: number;
            };
            /**
             * Downsample Method
             * @description 'mean' when downsampled, 'none' when full resolution
             */
            downsample_method: string;
            /**
             * Field
             * @description 'data', 'fit', or the derived 'residual'
             */
            field: string;
            /**
             * Full Shape
             * @description [lineouts, wavelengths] before downsampling
             */
            full_shape: number[];
            /**
             * Returned Shape
             * @description [lineouts, wavelengths] as returned
             */
            returned_shape: number[];
            /**
             * Values
             * @description Shape (len(y), len(x)) -- row-major by wavelength, directly usable as a Plotly heatmap z
             */
            values: (number | null)[][];
            /** Which */
            which: string;
            /**
             * X
             * @description Lineout axis coordinates
             */
            x: (number | null)[];
            /** X Label */
            x_label: string;
            /**
             * Y
             * @description Wavelength coordinates
             */
            y: (number | null)[];
            /** Y Label */
            y_label: string;
        };
        /** SpectrumInfo */
        SpectrumInfo: {
            /**
             * Fields
             * @description Renderable fields; 'residual' is derived as data - fit
             */
            fields: string[];
            /** Lineout Count */
            lineout_count: number;
            /**
             * Path
             * @description Artifact path this spectrum was read from
             */
            path: string;
            /** Wavelength Count */
            wavelength_count: number;
            /**
             * Which
             * @description 'ele' or 'ion'
             */
            which: string;
            /**
             * X Label
             * @description Lineout axis name, e.g. 'Time (ps)' or 'Radius (\mum)'
             */
            x_label: string;
            /**
             * Y Label
             * @description Spectral axis name, normally 'Wavelength'
             */
            y_label: string;
        };
        /**
         * UnavailableReason
         * @description Machine-readable reason a dataset view cannot be served.
         *
         *     Distinguishing these matters: showing "no data found" for an angular run
         *     reads as a bug, when the truth is that the view is deliberately out of scope.
         * @enum {string}
         */
        UnavailableReason: "angular_not_supported" | "dataset_missing" | "dataset_unreadable" | "unexpected_schema" | "field_unavailable" | "index_out_of_range";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentList"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                /** @description Experiment name (or id) */
                experiment?: string | null;
                /** @description Shot number, matched against params."data.shotnum" */
                shot?: string | null;
                /** @description MLflow lifecycle status: RUNNING, FINISHED, FAILED, KILLED */
                status?: string | null;
                /** @description tsadar progress tag, e.g. 'minimizing', 'completed' */
                stage?: string | null;
                /** @description Submitting user (mlflow.user tag) */
                user?: string | null;
                /** @description Free-text substring match on run name. '%' and '_' act as SQL LIKE wildcards (any-sequence and any-character) rather than literals; MLflow's filter grammar has no ESCAPE clause to make them literal. */
                q?: string | null;
                /** @description Sort key; prefix with '-' for descending. One of created, name, status, shot, loss. 'loss' orders on the 'overall loss' metric specifically -- unlike final_loss it cannot fall back to 'min loss'/'epoch loss', so runs lacking 'overall loss' sort as null; check loss_key when displaying the value. Duration is not sortable: it is computed from timestamps and MLflow cannot order by it. */
                sort?: string | null;
                /** @description Rows per page */
                page_size?: number;
                /** @description Cursor from a previous response's next_page_token */
                page_token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_runs__run_id__artifacts__artifact_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_api_runs__run_id__datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetAvailability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineout_api_runs__run_id__lineout_get: {
        parameters: {
            query?: {
                /** @description 'ele' or 'ion' */
                which?: string;
                /** @description Lineout index; negative counts from the end */
                index?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lineout"];
                };
            };
            /** @description Invalid field, spectrum or index */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Dataset missing or unreadable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Recognized but unsupported, e.g. an angular run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_history_api_runs__run_id__metrics__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profiles_api_runs__run_id__profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profiles"];
                };
            };
            /** @description Invalid field, spectrum or index */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Dataset missing or unreadable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Recognized but unsupported, e.g. an angular run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spectrogram_api_runs__run_id__spectrogram_get: {
        parameters: {
            query?: {
                /** @description 'ele' or 'ion' */
                which?: string;
                /** @description One of ['data', 'fit', 'residual']; 'residual' is derived as data - fit */
                field?: string;
                /** @description Pixel budget. The array is block-averaged to at most this many points; the lineout axis is spared where possible, so wavelength is reduced first. */
                max_px?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spectrogram"];
                };
            };
            /** @description Invalid field, spectrum or index */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Dataset missing or unreadable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Recognized but unsupported, e.g. an angular run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUnavailableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
